### PR TITLE
Add unite cms

### PR DESCRIPTION
**Pull request by franzwilding**

### CODE REVIEW

**Comment by Jotschi** [comment]
Hello @franzwilding , thanks for the entry. I took a quick look at the documentation and your entry.
I could not find the documentation for Client Side Forms, Custom Field Types, Custom Binary Handler. Can you point me to them?

I did also not find anything about searching contents except:

>  All other features that are part of many state-of-the-art CMS but have nothing to do with content management (search server, image processing, template rendering etc.) are not part of unite cms and we are not planing to implement them in the future. Because of this, unite cms is designed to be integrated with other services.

How can a user search contents in that case? Is there already support build-in for external services?

Greetings,

Johannes

**Comment by franzwilding** [comment]
Hey @Jotschi!

Thank you for your question. 

- The server-part of Client Side Forms can be done by creating a custom content type and adding fields to it. As we support GraphQL create mutations, clients can send form results to the API. As we do not support automatic form generation, I just changed this feature to NA. 

- Custom Field Types can be configured, using the **Variants** Field Type and the **Collection** Field Type. With this two types you can create complex nested field types.

- We have a s3 handler, but handling of files is done at s3 bucket. So you are right I will change this to NA!

- Regarding search: We implemented a complex filter system, that works like SQL where filters. So a simple search can be done using only the unite cms API (e.g. WHERE title LIKE %foo% OR content LIKE %foo%. More complex searches can be integrated using our webhooks and API.

**Comment by Jotschi** [comment]
@franzwilding Sounds good.

* Regarding Forms: Some vendors provide a dedicated tool chain / plugins to setup forms and also persist the result in the system. 

* With "Custom Field Types"  I meant whether it is possible to implement new field types (e.g: binary field type, or a field type which automatically handles markdown). Some systems support those types. Nested fields are something different. I might add another field to the list or update the *Nesting of Fields* description.

Do you mind switching these cases which do not match to No? NA means that it does not apply to the system / requirement or that it has not yet been determined.

You can anytime open another PR and update the file if you have released new features.

**Comment by franzwilding** [comment]
To be clear here: With unite cms, you can implement Custom Field Types by writing code: You have create a class, that implements an Interface and register the field type to the DI container. Do you mean this with "possible to implement new field types"? Then the answer would be Yes. Or do you mean that an admin can configure new field types?

**Comment by Jotschi** [comment]
Perfect. I meant that a developer would be able to extend the field type system. In that case you can set it to Yes.

**Comment by franzwilding** [comment]
Cool. So I think the entry is correct now and can be merged. Thank you for your feedback!

**Comment by Jotschi** [comment]
Yes. I merged it and added it to the list. Thanks for the help.

**Pull request merged**
