### PR TITLE
Added enonic.json

### PR DESCRIPTION
**Pull request by mortyeriksen**
I added the features for the Enonic XP headless CMS.

### CODE REVIEW

**Comment by Jotschi** [comment]
@mortyeriksen Thanks for the PR. Please add the links as mentioned in the contribution section https://github.com/gentics/headless-cms-comparison#contributing - Otherwise I can't confirm the change.

**Comment by mortyeriksen** [comment]
Thank for the feedback. I will assemble the links.

**Comment by mortyeriksen** [comment]
Here are all the links. Enonic XP is a hybrid CMS, so you have more flexibility for the API and custom development since you can deploy code. This is reflected in some of the answers below.

{
    "Timestamp": "2020-02-10T17:10:29.733Z",
    "Name": "Enonic XP",
    "Version": "7.2",
    "License": "https://github.com/enonic/xp",
    "Inception": "https://github.com/enonic/xp/releases/tag/v5.0.0",
    "Category": "Professional - Enterprise",
    "Open Source": "https://github.com/enonic/xp",
    "Cloud Service": "https://enonic.com/pricing",
    "On Premises Installation": "https://developer.enonic.com/downloads",
    "Cloud Service Hosted in Europe": "Yes",
    "Commercial Support Available?": "https://enonic.com/picing",
    "GraphQL API": "https://developer.enonic.com/docs/guillotine-app/master/api",
    "GraphQL [Mutations]": "No, roadmap",
    "GraphQL [Subscriptions]": "https://github.com/enonic/starter-headless/blob/master/src/main/resources/controllers/graphql.js (search for WS Protocol, missing doc at the moment)",
    "REST API": "https://developer.enonic.com/docs/xp/stable/runtime/engines/http-service",
    "REST [Create]": "https://developer.enonic.com/docs/xp/stable/api/lib-content",
    "REST [Read]": "https://developer.enonic.com/docs/xp/stable/api/lib-content",
    "REST [Update]": "https://developer.enonic.com/docs/xp/stable/api/lib-content",
    "REST [Delete]": "https://developer.enonic.com/docs/xp/stable/api/lib-content",
    "REST [Upload]": "https://developer.enonic.com/docs/xp/stable/api/lib-content#addattachment",
    "Search API": "https://developer.enonic.com/docs/xp/stable/storage/noql",
    "Search Features [Full Text Search]": "https://developer.enonic.com/docs/xp/stable/storage/noql",
    "Search Features [Stemming]": "https://developer.enonic.com/docs/xp/stable/storage/indexing#stemmed",
    "Search Features [Stop Words]": "Custom, must be handled when indexing",
    "Search Features [Boosting]": "https://developer.enonic.com/docs/xp/stable/storage/noql#query_functions",
    "Search Features [Autocompletion]": "https://developer.enonic.com/docs/xp/stable/storage/indexing#ngram",
    "Search Features [Autosuggestion]": "No",
    "Search Features [Result Highlighting]": "https://developer.enonic.com/docs/xp/stable/storage/highlighting",
    "Search Features [Geospatial Search]": "https://developer.enonic.com/docs/xp/stable/storage/noql#sort_functions",
    "Search Features [Search within uploads (pdf,doc)]": "Missing doc, check code: https://github.com/enonic/xp/tree/6c44fcc8f5e92d1c98ec41a6eafdb001637b6abe/modules/core/core-extractor/src/main/java/com/enonic/xp/extractor/impl",
    "Image Manipulation": "https://enonic.com/blog/enonic-simplifies-image-problems and https://developer.enonic.com/docs/xp/stable/runtime/engines/site-engine/image-service",
    "Image Focalpoint support": "https://enonic.com/blog/enonic-simplifies-image-problems",
    "Image Facedetection": "No",
    "Optimized Image Encoding": "https://developer.enonic.com/docs/xp/stable/runtime/engines/site-engine/image-service",
    "Asset fingerprinting": "No",
    "CDN Support": "Supported",
    "Antivirus Scanning": "Add-on - custom delivery",
    "Custom Binary Handler": "https://developer.enonic.com/docs/xp/stable/runtime/engines/http-service",
    "System Requirements": "Compute 2vCPU and 2GB memory min.",
    "Supported Databases": "https://developer.enonic.com/docs/xp/stable/storage",
    "Clustering": "https://developer.enonic.com/docs/xp/stable/deployment/strategies",
    "Docker Support": "https://hub.docker.com/r/enonic/xp/tags",
    "Backup Feature": "https://enonic.com/pricing (bottom table), https://developer.enonic.com/docs/enonic-cli/master#dumps, https://market.enonic.com/vendors/enonic/snapshotter",
    "Import/Export": "https://developer.enonic.com/docs/enonic-cli/master#export",
    "CLI": "https://developer.enonic.com/docs/enonic-cli/master and https://developer.enonic.com/start",
    "SDK [Java]": "Any GraphQL client and server: https://developer.enonic.com/docs/xp/stable/framework/java-bridge",
    "SDK [C#]": "Any GraphQL client",
    "SDK [PHP]": "Any GraphQL client",
    "SDK [JavaScript]": "Any GraphQL client(Apollo) and server: https://developer.enonic.com/docs/xp/stable/framework",
    "SDK [React]": "Any GraphQL client(Apollo) and server: https://market.enonic.com/vendors/enonic/react4xp-starter",
    "SDK [AngularJS]": "Any GraphQL client(Apollo)",
    "SDK [TypeScript]": "Any GraphQL client(Apollo) and server: https://developer.enonic.com/docs/xp/stable/framework with https://market.enonic.com/vendors/enonic/webpack-starter",
    "Web Hooks": "https://developer.enonic.com/docs/http-client-library/master and https://developer.enonic.com/docs/xp/stable/framework/controllers",
    "Eventbus": "https://developer.enonic.com/docs/xp/stable/framework/events",
    "Bulk Import": "https://developer.enonic.com/docs/xp/stable/framework/controllers and https://developer.enonic.com/docs/xp/stable/api/lib-content",
    "Client Side Forms": "https://market.enonic.com/vendors/enonic/form-builder",
    "Plugin System": "https://developer.enonic.com/docs/xp/stable/apps",
    "Customizable UI": "https://developer.enonic.com/docs/xp/stable/cms/schemas and https://developer.enonic.com/docs/content-studio/master/widgets",
    "User Management": "https://developer.enonic.com/docs/xp/stable/iam",
    "Role Based Permissions": "https://developer.enonic.com/docs/xp/stable/iam",
    "Document Level Permissions": "https://developer.enonic.com/docs/content-studio/master/permissions",
    "OAuth 2.0 Support": "https://market.enonic.com/vendors/enonic/oidc-id-provider",
    "Auditing": "https://developer.enonic.com/docs/xp/stable/api/lib-audit and https://developer.enonic.com/docs/xp/stable/release#content_api_audit_log",
    "API Keys": "Custom: https://developer.enonic.com/docs/xp/stable/runtime/engines/http-service",
    "Project Support": "A bit quick to answer yes, coming in a month - 7.3: https://github.com/enonic/xp/issues/7866",
    "I18N Localized Content": "https://developer.enonic.com/docs/xp/stable/api/lib-i18n",
    "Content Trees": "https://developer.enonic.com/docs/content-studio/master/navigator",
    "Tagging": "https://developer.enonic.com/docs/xp/stable/cms/input-types#tag",
    "Content Relations": "https://developer.enonic.com/docs/xp/stable/cms/input-types#contentselector",
    "Nesting of Fields": "https://developer.enonic.com/docs/xp/stable/cms/schemas#sets",
    "GDPR Statement": "https://drive.google.com/file/d/1bzOZLg4ZddSxnDfGVCZhbGgZvoRCQXAg/view?usp=sharing",
    "GDPR API": "No, roadmap",
    "Editing Conflict Detection": "No, roadmap",
    "Versioning": "https://developer.enonic.com/docs/content-studio/master/widgets#version_history",
    "Content Scheduling": "https://developer.enonic.com/docs/content-studio/master/workflow#publish_request",
    "Content Branches": "https://developer.enonic.com/docs/xp/stable/api/lib-content#publish",
    "Content Models / Schemas": "https://developer.enonic.com/docs/xp/stable/cms/schemas",
    "Content Model / Schema Versioning": "Your code repository, handled as code",
    "Content Migration": "Yes, using migration script in Javascript",
    "Workflows": "https://developer.enonic.com/docs/content-studio/master/workflow",
    "Special Features": "Customisable GraphQL or Rest API, Powerful image handling, Content preview, Hybrid CMS support"
}

**Comment by Jotschi** [comment]
Thanks for the links. Thats actually a very useful format. I'll check those and give you feedback.


> "Optimized Image Encoding": "https://developer.enonic.com/docs/xp/stable/runtime/engines/site-engine/image-service",

I did not see documentation that progressive image encoding is supported. No mention about webp or similar encoding methods.

**Comment by mortyeriksen** [comment]
Thanks Johannes. Let me know if something is unclear

**Comment by mortyeriksen** [comment]
I will check the image service. Progressive should be supported.

**Comment by mortyeriksen** [comment]
> > "Optimized Image Encoding": "https://developer.enonic.com/docs/xp/stable/runtime/engines/site-engine/image-service",
> 
> I did not see documentation that progressive image encoding is supported. No mention about webp or similar encoding methods.

I checked with the developers. We had progressive jpegs in the previous platform, but currently it's on the backlog for Enoinc XP, but we have jpeg quality control and different formats (not webp).

**Comment by Jotschi** [comment]
I have added the json file and change a few fields I could not confirm or which are lacking.

```
{
    "GraphQL [Subscriptions]": "I changed this to no. You can open another PR once you have added documentation on how to use this feature.",
    "Search Features [Search within uploads (pdf,doc)]": "I changed this to no due to missing doc. Please add documentation and I open a PR.",
    "Optimized Image Encoding": "I changed this to No. You can open a PR to add this once it has been released.",
    "Custom Binary Handler": "I did not find this info?",
    "Bulk Import": "I changed this to No. Just having a REST API does not mean there is a bulk import feature. Examples for bulk imports are for example endpoints which can handle ndjson",
    "API Keys": "I did not find this info?",
    "GDPR Statement": "Is this linked on the website?",
    "Content Migration": "I changed this to No. Manual migration can be done by any system which has a REST API. Some systems support automatic server side migrations.",
}
```

**Comment by Jotschi** [comment]
The entry is now online.

**Comment by mortyeriksen** [comment]
> {
>     "GraphQL [Subscriptions]": "I changed this to no. You can open another PR once you have added documentation on how to use this feature.",
>     "Search Features [Search within uploads (pdf,doc)]": "I changed this to no due to missing doc. Please add documentation and I open a PR.",
>     "Optimized Image Encoding": "I changed this to No. You can open a PR to add this once it has been released.",
>     "Custom Binary Handler": "I did not find this info?",
>     "Bulk Import": "I changed this to No. Just having a REST API does not mean there is a bulk import feature. Examples for bulk imports are for example endpoints which can handle ndjson",
>     "API Keys": "I did not find this info?",
>     "GDPR Statement": "Is this linked on the website?",
>     "Content Migration": "I changed this to No. Manual migration can be done by any system which has a REST API. Some systems support automatic server side migrations.",
> }

Thanks for the update. We will document more and send a new PR a later.

**Comment by mortyeriksen** [comment]
@Jotschi Just a quick addition. I added the GDPR statement to our pricing page: https://enonic.com/pricing (see below the support level matrix).

**Pull request closed without merging**
