### PR TITLE
Added KeystoneJS to list of CMSes

### PR DESCRIPTION
**Pull request by raveling**
Ronald fromKeystone core team here.
I've added product details for Keystone 6.
Let me know if you have any questions.
Thank you!

### CODE REVIEW

**Comment by raveling** [comment]
Any traction on this @npomaroli @Abyhsen ?  🙏

**Comment by raveling** [comment]
Ping. 🙏

**Comment by deckdom** [comment]
Hi,
sorry for the long delay, we had to get this Project running again.
I merged the settings but didn't notice that the configuration is wrong.

Currently all Options in the "keystone.json" file are in the "description" field and not the correct "value" one.
Please correct these and provide a new PR.

**Comment by raveling** [comment]
Thanks for clarifying @deckdom!
New PR here #50

**Pull request merged**
