### PR TITLE
added Agility CMS

### PR DESCRIPTION
**Pull request by jamesvidler**
Added Agility CMS to this great CMS feature comparison!

### CODE REVIEW

**Comment by Jotschi** [comment]
@jamesvidler Thanks for the PR. Please provide links to all mentioned features.

Example: https://github.com/gentics/headless-cms-comparison/pull/30#issuecomment-586168762

**Comment by jamesvidler** [comment]
Ah ok, will do! Sorry, I was looking at other examples and they didn't have any links. Agreed that it is more useful to have direct links. Will assemble for you.

**Comment by jamesvidler** [comment]
Whoops, didn't mean to close the request

**Comment by Jotschi** [comment]
No problem. I'll change at some point the format of the JSON so that the link can also be directly stored. That way it would be mandatory/useful to provide it with the JSON.

**Comment by jamesvidler** [comment]
@Jotschi just revisiting this. What format do you require the links in? I don't see a place for it in the JSON.

**Comment by Jotschi** [comment]
We have changed the format of the JSON since we now have a new website. You need to re-apply the changes in the new format. I suggest to create a new PR. I'm not sure how links will be handled in the new format.

**Comment by jamesvidler** [comment]
@Jotschi ok thank you. Will do.

**Pull request closed without merging**
